<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   <TargetFramework>netstandard2.0</TargetFramework>
   <Platforms>AnyCPU;x64;x86;ARM;ARM64</Platforms>
   <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroStore.Services\MicroStore.Services.csproj" />
    <ProjectReference Include="..\MicroStoreAPI\MicroStoreAPI.csproj" />
    <ProjectReference Include="..\MicrosoftStore\MicrosoftStore.csproj" />
    <ProjectReference Include="..\StoreLib\StoreLib\StoreLib.csproj" />
  </ItemGroup>

</Project>
